// Fisher-Yates shuffle algorithm to randomize an array (In our case, an array of strings)
// https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
export const shuffleArray = (array: string[]): string[] => {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    const temp = array[i]
    array[i] = array[j]
    array[j] = temp
  }
  return array
}

export const wordList: string[] = [
  'account',
  'act',
  'addition',
  'adjustment',
  'advertisement',
  'agreement',
  'air',
  'amount',
  'amusement',
  'animal',
  'answer',
  'apparatus',
  'approval',
  'argument',
  'art',
  'attack',
  'attempt',
  'attention',
  'attraction',
  'authority',
  'back',
  'balance',
  'base',
  'behavior',
  'belief',
  'birth',
  'bit',
  'bite',
  'blood',
  'blow',
  'body',
  'brass',
  'bread',
  'breath',
  'brother',
  'building',
  'burn',
  'burst',
  'business',
  'butter',
  'canvas',
  'care',
  'cause',
  'chalk',
  'chance',
  'change',
  'cloth',
  'coal',
  'color',
  'comfort',
  'committee',
  'company',
  'comparison',
  'competition',
  'condition',
  'connection',
  'control',
  'cook',
  'copper',
  'copy',
  'cork',
  'cotton',
  'cough',
  'country',
  'cover',
  'crack',
  'credit',
  'crime',
  'crush',
  'cry',
  'current',
  'curve',
  'damage',
  'danger',
  'daughter',
  'day',
  'death',
  'debt',
  'decision',
  'degree',
  'design',
  'desire',
  'destruction',
  'detail',
  'development',
  'digestion',
  'direction',
  'discovery',
  'discussion',
  'disease',
  'disgust',
  'distance',
  'distribution',
  'division',
  'doubt',
  'drink',
  'driving',
  'dust',
  'earth',
  'edge',
  'education',
  'effect',
  'end',
  'error',
  'event',
  'example',
  'exchange',
  'existence',
  'expansion',
  'experience',
  'expert',
  'fact',
  'fall',
  'family',
  'father',
  'fear',
  'feeling',
  'fiction',
  'field',
  'fight',
  'fire',
  'flame',
  'flight',
  'flower',
  'fold',
  'food',
  'force',
  'form',
  'friend',
  'front',
  'fruit',
]

const alphaChars: string = 'abcdefghijklmnopqrstuvwxyz'
const numerics: string = '0123456789'
const otherChars: string = '?!@#$%^&*()_-+={}[]|\\\'"<>:;,./~'

export const keyboardChars: string | string[] = [
  ...numerics,
  ...alphaChars,
  ...alphaChars.toUpperCase(),
  ...otherChars,
  ' ',
]
